language: c
compiler: gcc
os: linux
dist: bionic
env:
  global:
  - secure: rm4qOWMcVcDIvbdENbm9/7jda8+jqHT/1sq4/bZQY+Otl/BsRDb967eo5gFIw4F007BPqSMp0R6EoA5Ok2RoZm4anjJ1PTvcGgyFNW94OfJirqLJe3JL1sLSFxuA54Wdu8xmO7SCJG4HXt84zp9B+OFTrSkzmELcQFnPWpZNP3E=
addons:
  apt:
    update: true
    packages:
    - libsystemd-dev
    - libkmod-dev
    - libmount-dev
    - libisns-dev
    - openssl
    - flex
    - bison
  coverity_scan:
    project:
      name: cleech/open-iscsi
    notification_email: leech@pobox.com
    build_command_prepend: "(dpkg-buildflags --export=sh) > env.sh && source env.sh"
    build_command: make
    branch_pattern: coverity_scan
script:
- |
  if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then
    eval $(dpkg-buildflags --export=sh)
    make
  fi
